/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package software_administrativo;
import java.sql.Array;
import java.sql.SQLException;        
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.*;
import java.awt.event.KeyEvent;
import static software_administrativo.ventana.conexion;
import static software_administrativo.factrura_de_ventas.vender;
/**
 *
 * @author Admin
 */
public class busqueda_de_productos extends javax.swing.JDialog {
//DefaultTableModel modelo = (DefaultTableModel) vender.getModel();
         static Connection conexion = null;
         static Connection conexion2 = null;
  static  Statement statement = null;
 static int fila;
 
  ResultSet resultado ;
  String[] nombre ;
 String[] codigo ;
 String[] precio;
  String[] existencia;
 
    /**
     * Creates new form busqueda_de_clientes
     */
    public busqueda_de_productos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
             DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
   try{
       
     
       Class.forName("org.firebirdsql.jdbc.FBDriver").newInstance();
       conexion = DriverManager.getConnection("jdbc:firebirdsql:localhost:C:/ValeryEstandar2020/Datos/VALERY3.mdf","sysdba","masterkey");
         conexion2 = DriverManager.getConnection("jdbc:firebirdsql:localhost:C:/ValeryEstandar2020/Datos/VALERY3.mdf","sysdba","masterkey");
      Statement cursor = conexion.createStatement();
       Statement cursor2 = conexion2.createStatement();
      ResultSet resultado ;
      ResultSet resultado_existencias;
     resultado = cursor.executeQuery("Select * FROM PRODUCTOS_TERMINADOS");
     resultado_existencias = cursor2.executeQuery("Select * FROM PRODUCTOS_TERMINADOS_DEPOSITOS");
       //ResultSetMetaData meta = resultado.getMetaData();
    // int col = meta.getColumnCount();
     int b = 0;
     int c = 0;
     nombre = new String[obtener()];
     codigo = new String[obtener()];
     precio = new String[obtener()];
     existencia = new String[obtener()];
      while(resultado.next()){
          fila = resultado.getRow();
         nombre[b] =  resultado.getString(4);
         codigo[b] = resultado.getString(1);
         precio[b] = resultado.getString(34);
         
        b++;
      }
       while(resultado_existencias.next()){
        //fila = resultado.getRow();
      c++;
    existencia[c] = resultado_existencias.getString(8);
         }
        for(int a = 0;a < fila;a++){   
         modelo.addRow(new Object[]{codigo[a],nombre[a],precio[a],existencia[a]});
         }
       
    } catch (Exception e) {
      System.out.println("Could not initialize the database. no se pudo");
      e.printStackTrace();
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BUSCAR = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        BUSCAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BUSCAR.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 153, 255)));
        BUSCAR.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        BUSCAR.setSelectionColor(new java.awt.Color(38, 117, 191));
        BUSCAR.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                BUSCARCaretUpdate(evt);
            }
        });
        BUSCAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BUSCARKeyReleased(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.light")));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Existencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setSelectionBackground(new java.awt.Color(38, 117, 191));
        jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable2.setShowGrid(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public static int obtener()throws SQLException{
      Connection conexion = null;
       conexion = DriverManager.getConnection("jdbc:firebirdsql:localhost:C:/ValeryEstandar2020/Datos/VALERY3.mdf","sysdba","masterkey");
      Statement cursor = conexion.createStatement();
      ResultSet resultado ;
     resultado = cursor.executeQuery("Select * FROM CLIENTES");
       ResultSetMetaData meta = resultado.getMetaData();
     while(resultado.next()){
        fila = resultado.getRow();
     }
     return fila+1;
}

    private void BUSCARCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_BUSCARCaretUpdate
        String busqueda= BUSCAR.getText();
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        System.out.print(busqueda.length()+"\n");
        String buscando;
        if(busqueda.equals(""))
        modelo.setRowCount(0);
        modelo.setRowCount(0);
        for(int i = 0; i < nombre.length+1;i++){
            buscando = nombre[i].substring(0,busqueda.length());
            if(busqueda.toLowerCase().contains(buscando.toLowerCase())){
                modelo.addRow(new Object[]{codigo[i],nombre[i],precio[i],existencia[i]});
                
            }
        }

    }//GEN-LAST:event_BUSCARCaretUpdate

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
      String  codigos;
      String nombres;
      String existencias;
      String precios;
       
        
        if(jTable2.getRowSelectionAllowed()){
        codigos  = codigo[jTable2.getSelectedRow()];
        nombres  = nombre[jTable2.getSelectedRow()];
        existencias = existencia[jTable2.getSelectedRow()];
        precios = precio[jTable2.getSelectedRow()];
          // JOptionPane.showMessageDialog(null,nombres); 
      //factrura_de_ventas.ver_nombres.setText(nombres);
      vender.setValueAt(codigos,vender.getSelectedRow(),0);
       vender.setValueAt(nombres,vender.getSelectedRow(),1);
       vender.setValueAt(precios,vender.getSelectedRow(),3);
       vender.setValueAt(existencias,vender.getSelectedRow(),2);
      //factrura_de_ventas.ver_telefono.setText(telefonos);
      dispose();
     
       }
    }//GEN-LAST:event_jTable2MouseClicked

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
          if(evt.getKeyCode() == KeyEvent.VK_ESCAPE) dispose();
    }//GEN-LAST:event_formKeyReleased

    private void BUSCARKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BUSCARKeyReleased
      if(evt.getKeyCode() == KeyEvent.VK_ESCAPE) dispose();
    }//GEN-LAST:event_BUSCARKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
        javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busqueda_de_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busqueda_de_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busqueda_de_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busqueda_de_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                busqueda_de_productos dialog = new busqueda_de_productos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField BUSCAR;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
