/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package software_administrativo;
import java.sql.Array;
import java.sql.SQLException;        
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.*;


/**
 *
 * @author Admin
 */
public class ventana extends javax.swing.JFrame {
   
         static Connection conexion = null;
  static  Statement statement = null;
  int fila;
  ResultSet resultado ;
  String[] nombre ;
 String[] codigo ;
 String[] telefono;
    /**
     * Creates new form ventana
     */
    public ventana() {
      initComponents();
      DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
   try{
       
     
       Class.forName("org.firebirdsql.jdbc.FBDriver").newInstance();
       conexion = DriverManager.getConnection("jdbc:firebirdsql:localhost:C:/ValeryEstandar2020/Datos/VALERY3.mdf","sysdba","masterkey");
      Statement cursor = conexion.createStatement();
      ResultSet resultado ;
     resultado = cursor.executeQuery("Select * FROM CLIENTES");
       //ResultSetMetaData meta = resultado.getMetaData();
    // int col = meta.getColumnCount();
     int b = 0;
     nombre = new String[obtener()];
     codigo = new String[obtener()];
     telefono = new String[obtener()];
      while(resultado.next()){
          fila = resultado.getRow();
         nombre[b] =  resultado.getString(2);
         codigo[b] = resultado.getString(1);
         telefono[b] = resultado.getString(16);
        b++;
      }
        for(int a = 0;a < fila;a++){   
         modelo.addRow(new Object[]{codigo[a],nombre[a],telefono[a]});
         }

    } catch (Exception e) {
      System.out.println("Could not initialize the database. no se pudo");
      e.printStackTrace();
        
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BUSCAR = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setTitle("Clientes");
        setAlwaysOnTop(true);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(100, 100));

        BUSCAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BUSCAR.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 153, 255)));
        BUSCAR.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        BUSCAR.setSelectionColor(new java.awt.Color(38, 117, 191));
        BUSCAR.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                BUSCARCaretUpdate(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.light")));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Telefono", "Saldo actual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setSelectionBackground(new java.awt.Color(38, 117, 191));
        jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable2.setShowGrid(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUSCARCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_BUSCARCaretUpdate
     String busqueda= BUSCAR.getText();
    DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
    System.out.print(busqueda.length()+"\n");
    String buscando;
   if(busqueda.equals(""))
    modelo.setRowCount(0);
   modelo.setRowCount(0);
   for(int i = 0; i < nombre.length+1;i++){
       buscando = nombre[i].substring(0,busqueda.length());
       if(busqueda.toLowerCase().contains(buscando.toLowerCase())){     
         modelo.addRow(new Object[]{codigo[i],nombre[i],telefono[i]}); 
       }
   }

         
    }//GEN-LAST:event_BUSCARCaretUpdate

    int obtener()throws SQLException{
      Connection conexion = null;
       conexion = DriverManager.getConnection("jdbc:firebirdsql:localhost:C:/ValeryEstandar2020/Datos/VALERY3.mdf","sysdba","masterkey");
      Statement cursor = conexion.createStatement();
      ResultSet resultado ;
     resultado = cursor.executeQuery("Select * FROM CLIENTES");
       ResultSetMetaData meta = resultado.getMetaData();
     while(resultado.next()){
         fila = resultado.getRow();
     }
     return fila+1;
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//ventana frame = new ventana();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
        
    }
    
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField BUSCAR;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
